require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LineLength:
  Max: 80

Layout/TrailingWhitespace:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Minitest/MultipleAssertions:
  Max: 10
