# Company is a class that represents a company with users
class Company
  PREVENT_DUPLICATE_USERS: bool

  @users_to_email: Array[User]

  @users_not_to_email: Array[User]

  attr_reader id: Integer

  attr_reader name: String

  attr_reader top_up: Integer

  attr_reader email_status: bool

  def initialize: (id: Integer, name: String, top_up: Integer, email_status: bool) -> void

  def add_user: (user: User) -> untyped

  def add_user_sorted_by_last_name: (user: User) -> untyped

  def duplicate_user?: (user: User) -> bool

  def empty?: -> bool

  def to_s: () -> ::String

  def user_count: -> Integer

  def users: (user: User) -> Array[User]
end
